name: Build & deploy Svelte to Github Pages
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        working-directory: ./app/svelte
        run: |
          npm install
          npm run build

      - name: Move the Svelte build to the docs folder
        run: mv ./app/svelte/build ./docs/app
      
      # Based of https://josecelano.github.io/svelte-deploy-with-github-actions/
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs
          branch: gh-pages
          target-folder: ./docs
          
